language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before:
  - python manage.py syncdb
  - python manage.py loaddata faculties departments courses professors coursesemesters
script: python -Wall manage.py test wiki
